### ISSUE TITLE
How can an `RssDocument` be rendered to Text, ByteString, etc?

### ISSUE THREAD

**Issue by devlinzed** [k0ral/rss-conduit#2]

**Comment by k0ral** [comment]
Hello devlinkzed,

The `rss-conduit` library is meant to be used together with `xml-conduit`. To render any `Source` of `Event`s, you can use one of the `render*` functions from the `Text.XML.Stream.Render` module.
For example:

```haskell
import Data.Conduit.List
import Text.RSS.Conduit.Render
import Text.RSS.Types
import Text.XML.Stream.Render

docToText :: (Monad m) => RssDocument -> m [Text]
docToText document = runConduit $ renderRssDocument document =$= renderText def =$= consume

docToByteString :: (Monad m) => RssDocument -> m [ByteString]
docToByteString document = runConduit $ renderRssDocument document =$= renderBytes def =$= consume
```

I hope this helps. Please close this issue unless you notice something wrong with the behavior of the library. Thank you.

**Comment by devlinzed** [comment]
Thanks a lot for the response.  That's very helpful.
