### ISSUE TITLE
No channel tag

### ISSUE THREAD

**Issue by wyager** [k0ral/rss-conduit#6]
I think there needs to be a `<channel>` tag under the `<rss>` tag. I think it should be a short change to `renderRssDocument`. Something like 

```
renderRssDocument d = tag "rss" (attr "version" . pack . showVersion $ d^.documentVersionL) $ tag "channel" mempty $ do
  textTag "title" $ d^.channelTitleL
```

**Comment by wyager** [comment]
After adding the `<channel>` tag manually, it seems to mostly pass the W3C feed validator except a few bits and bobs that I'm pretty sure most readers wouldn't have a problem with. (Like having an empty `skipDays` instead of eliding the tag altogether, I guess?)

**Comment by k0ral** [comment]
Fixed:
- rendering `<channel>` tag in c0e3757f666c386fc71a9cff613b841c8875878e
- eliding empty `<skipDays>` and `<skipHours>` tags in 5c76ef62545bc2459af8f1946719c9c42b96862a

Can you please let me know about the "bits and bobs" ? :) I'd like to fix as many as I can before making a new release.

**Comment by wyager** [comment]
Sure, let me just figure out how to get stack to pull from a git repo...

**Comment by wyager** [comment]
Wow, stack is pretty sweet. That was really easy. OK, the only thing the validator doesn't like that isn't my fault (out-of-spec GUID/image too big, which I'll maybe fix later) is https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html

The solution here is to let people embed their own attrs in the `<rss...>` header. I'll go ahead and work on that for a minute and have a PR ready in a bit.

**Comment by wyager** [comment]
OK, I'm working on the custom document attrs thing, but in the meantime I'm going to close this issue. Safari, at least, seems to have no problem parsing my feed.

**Comment by wyager** [comment]
To clarify, I think this is a good place to upload a new version to hackage. The custom attrs stuff will take more time.
