### ISSUE TITLE
Add NFData instances to Text.Rss.Types

### ISSUE THREAD

**Issue by TOTBWF** [k0ral/rss-conduit#9]
After parsing an `RssDocument`, there is a potential for space leaks if the value isn't brought to normal form. Currently, I have a bunch of orphan instances in my application for all of the types in `Text.Rss.Types`, which isn't ideal. I propose adding `NFData` instances from `deepseq` to all of the datatypes in `Text.Rss.Types`, and maybe examining if the types should be made strict.

If you want, I can take the lead on this, though it would require that https://github.com/Soostone/uri-bytestring/pull/52 gets merged/released.

**Comment by k0ral** [comment]
Sure, that would certainly be a nice improvement.
If you already have the instances written on your side, or if you are in a hurry, you are welcome to contribute a pull-request.
Otherwise, I can do it within a reasonable delay once your pull-request on uri-bytestring gets merged+released.

**Comment by TOTBWF** [comment]
I'm fine waiting a bit if it means that we get to do things properly.

**Comment by k0ral** [comment]
Closing this issue, as it has remained untouched for a long time. Feel free to re-open it in case it becomes actionable again.
